### ISSUE TITLE
Create CustomTypeParser for the component XSDs.

### ISSUE THREAD

**Issue by dziegenh** [dziegenh/Modulflex#8]
Custom types may be defined inside the component XSDs themselves ("local custom types"). The existing CustomTypeParser is aible to handle this, e.g. using an empty namespace String.
But: Namespaces may be necessary if the same WidgetFactory is used for loading different component XSDs. Each component xsd needs a custom namespace in this case.
Another quick solution would be adding the local custom type parser to the factory each time when a component XSD is loaded and to remove the local parser afterwards.

**Comment by fwilke** [comment]
I prefer using the second option, simply adding and removing generators "on demand".
